[workspace]
members = [
  "module",
  "game-module",
]
default-members = ["module"]
# cargo feature graph resolver. v2 is default in edition2021 but workspace
# manifests don't have editions.
resolver = "2"