// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
// A namespace for generated variants and helper functions.
export namespace EntityType {
  // These are the generated variant types for each variant of the tagged union.
  // One type is generated per variant and will be used in the `value` field of
  // the tagged union.
  export type Player = { tag: "Player" };
  export type Npc = { tag: "Npc" };
  export type Monster = { tag: "Monster" };
  export type Summoned = { tag: "Summoned" };
  export type Item = { tag: "Item" };

  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  export const Player = { tag: "Player" };
  export const Npc = { tag: "Npc" };
  export const Monster = { tag: "Monster" };
  export const Summoned = { tag: "Summoned" };
  export const Item = { tag: "Item" };

  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createSumType([
      new SumTypeVariant("Player", AlgebraicType.createProductType([])),
      new SumTypeVariant("Npc", AlgebraicType.createProductType([])),
      new SumTypeVariant("Monster", AlgebraicType.createProductType([])),
      new SumTypeVariant("Summoned", AlgebraicType.createProductType([])),
      new SumTypeVariant("Item", AlgebraicType.createProductType([])),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: EntityType): void {
      EntityType.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): EntityType {
      return EntityType.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

// The tagged union or sum type for the algebraic type `EntityType`.
export type EntityType = EntityType.Player | EntityType.Npc | EntityType.Monster | EntityType.Summoned | EntityType.Item;

export default EntityType;

