// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { Vec2 as __Vec2 } from "./vec_2_type";
import { EntityType as __EntityType } from "./entity_type_type";

export type Entity = {
  id: bigint,
  entityType: __EntityType,
  position: __Vec2,
  direction: number,
  ownerIdentity: Identity | undefined,
  createdAt: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Entity {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createU64Type()),
      new ProductTypeElement("entityType", __EntityType.getTypeScriptAlgebraicType()),
      new ProductTypeElement("position", __Vec2.getTypeScriptAlgebraicType()),
      new ProductTypeElement("direction", AlgebraicType.createF64Type()),
      new ProductTypeElement("ownerIdentity", AlgebraicType.createOptionType(AlgebraicType.createIdentityType())),
      new ProductTypeElement("createdAt", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Entity): void {
    Entity.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Entity {
    return Entity.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


